runmode: debug               # 开发模式, debug, release, test
addr: :9090                  # HTTP绑定端口
name: blog-system            # API Server的名字
url: http://127.0.0.1:9090   # pingServer函数请求的API服务器的ip:port
max_ping_count: 10           # pingServer函数尝试的次数

db:
  name: restful
  addr: 127.0.0.1:3306
  username: root
  password: root